### ISSUE TITLE
Twitter Kit is no longer supported

### ISSUE THREAD

**Issue by andypiper** [capacitor-community/twitter#4]
Hi there - unfortunately Twitter Kit is no longer supported. I'd recommend moving to a web-based login flow via [Sign-in with Twitter](https://developer.twitter.com/en/docs/basics/authentication/guides/log-in-with-twitter).

**Comment by stewwan** [comment]
It’s just not maintained by Twitter anymore but it is still supported otherwise my apps would have had break. Are you facing any issue specifically?
