### ISSUE TITLE
Could not resolve project :capacitor-community-twitter on Android Studio

### ISSUE THREAD

**Issue by cosentino** [capacitor-community/twitter#5]
Hi,
after doing the Android setup, I'm getting the following build error in Android Studio:

```
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :capacitor-community-twitter.
     Required by:
         project :app
      > Unable to find a matching configuration of project :capacitor-community-twitter:
          - None of the consumable configurations have attributes.
```

I've already tried to Build -> Clean Project and Rebuild Project.

I've also noticed that there are some differences between the README and the https://github.com/stewwan/capacitor-twitter-example.
For example the README does not mention to add the following to android/app/build.gradle.

```
implementation project(':capacitor-twitter')
implementation 'com.twitter.sdk.android:twitter-core:3.1.1'
```

Moreover the package name to import in MainActivity.java is different:

`import cap.twitter.plugin.TwitterPlugin;`

Could it be because of some recent changes made for the new @capacitor-community namespace?

Thanks

**Comment by stewwan** [comment]
hey @cosentino . Thanks for opening this issue, can you try from v1.0.1 ?

don't forget to run `npx cap sync android`
also [check changelog](https://github.com/capacitor-community/twitter/blob/master/CHANGELOG.md#breaking-change) for a breaking change on the java import
