### ISSUE TITLE
Error upon login

### ISSUE THREAD

**Issue by vernondris** [capacitor-community/twitter#6]
**Describe the bug**
I am receiving a = '{"message": "error"}' upon login 

**To Reproduce**
1. click sign in with twitter button from ionic
2. then error response will log telling the '{"message": "error"}'

**Expected behavior**
Token must be generated after sign in button has clicked

**Screenshots**
![image](https://user-images.githubusercontent.com/3529446/89175001-aec2a500-d53b-11ea-84c5-0dd40bd69dce.png)

**Smartphone (please complete the following information):**
 - Device: xiaomi redmi and in simulators as well

**Additional context**

**Comment by vernondris** [comment]
I will set this close. I found about the twitter account that can solves this. Thanks

**Comment by SirBernardPhilip** [comment]
How did you end up solving this? I am having issues myself
